steps:
  # Install node packages
  - name: "node"
    entrypoint: "npm"
    args: ["install"]

  # Run Angular unit tests
  - name: "trion/ng-cli-karma"
    args: ["ng", "test", "--watch", "false"]
    dir: "ui"

  # Build Angualr production app
  - name: "node"
    entrypoint: "npm"
    args: ["run", "build", "--prod"]
    dir: "ui"
  
  # Build Go server module.
  - name: golang
    args: ['go', 'build', '.']
    dir: "goserver"

  # Run Go server unit tests
  - name: "golang"
    args: ['go', 'test', './...']
    dir: "goserver"