steps:
  # Install node packages
  - name: "gcr.io/cloud-builders/npm"
    args: ["install"]

  # Build settings.json file from Subsitution variable _SETTINGS_JSON which contains
  # the environment's values for the settings.json file.
  - name: "ubuntu"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        if [[ -z '$_SETTINGS_JSON' ]]; then
          echo "_SETTINGS_JSON argument does not exist or is blank"
          exit 1
        fi
        echo Creating settings.json file from _SETTINGS_JSON build trigger variable value.
        echo '$_SETTINGS_JSON' > ./settings.json

  # Deploy to the current App Engine project
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
    timeout: "240s"

timeout: 5m
